---
- name: Run simple-api container
  docker_container:
    name: simple-api
    image: abdelghani77/tp-devops-simple-api:latest
    state: started
    restart_policy: always
    env:
      DATABASE_HOST: database
      USERNAME: usr
      DATABASE_PASSWORD: pwd
    networks:
      - name: app-network
