---
- name: Run database container
  docker_container:
    name: database
    image: abdelghani77/tp-devops-database:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_PASSWORD: pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - name: app-network
