---
- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: install_docker

    - name: Create Docker network
      ansible.builtin.include_role:
        name: create_network

    - name: Launch database
      ansible.builtin.include_role:
        name: launch_database

    - name: Launch app
      ansible.builtin.include_role:
        name: launch_app

    - name: Launch proxy
      ansible.builtin.include_role:
        name: launch_proxy
