name: test-backend

on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: simple-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run: mvn clean verify

      - name: SonarCloud analysis
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=ABDELGHANI2022_tp-devops-correction-docker \
            -Dsonar.organization=abdelghani2022 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
